# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='book',
        ),
        migrations.AddField(
            model_name='book_author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
    ]
